name: Fly Deploy
on:
  pull-request:
    branches:
      - flyio
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cp -r torhouse/* .
        - run: flyctl deploy --remote-only